# Generated by Django 6.0.1 on 2026-01-20 16:38

import addpatient.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addpatient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', addpatient.models.AppUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='username',
        ),
    ]
