# Generated by Django 6.0.1 on 2026-01-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addpatient', '0002_alter_appuser_managers_remove_appuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
