# Generated by Django 6.0.1 on 2026-01-28 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addpatient', '0003_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_visit_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mrn',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_datetime', models.DateTimeField()),
                ('visit_type', models.CharField(choices=[('OPD', 'OPD'), ('FOLLOW_UP', 'Follow-up'), ('EMERGENCY', 'Emergency'), ('WARD', 'Ward Round')], max_length=50)),
                ('visit_reason', models.TextField(blank=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('patient', models.ForeignKey(db_column='patient_mrn', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='addpatient.patient', to_field='mrn')),
            ],
            options={
                'ordering': ['-visit_datetime'],
            },
        ),
    ]
