# Generated by Django 6.0.1 on 2026-01-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addpatient', '0004_patient_created_at_patient_last_visit_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse')], default='nurse', max_length=10),
        ),
    ]
