# Generated by Django 6.0 on 2026-01-30 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addpatient', '0005_appuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
