# Generated by Django 6.0 on 2026-02-13 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addpatient', '0008_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_nurse',
            field=models.ForeignKey(blank=True, limit_choices_to={'role_type': 'nurse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients_nurse', to=settings.AUTH_USER_MODEL),
        ),
    ]
