# Generated by Django 6.0 on 2026-02-13 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addpatient', '0009_patient_assigned_nurse'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('due', models.CharField(default='Today, 05:00 PM', max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='addpatient.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
