# Generated by Django 6.0.2 on 2026-02-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addpatient', '0010_patienttask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='doctor',
            new_name='recipient',
        ),
    ]
