# Generated by Django 6.0 on 2026-02-18 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addpatient', '0011_rename_doctor_notification_recipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wound_type', models.CharField(blank=True, max_length=100)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('wound_stage', models.CharField(blank=True, max_length=50)),
                ('exudate_amount', models.CharField(blank=True, max_length=50)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pain_level', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('body_location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_assessments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='addpatient.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_image', models.ImageField(upload_to='wound_images/full/')),
                ('selected_area_image', models.ImageField(blank=True, null=True, upload_to='wound_images/selected/')),
                ('annotations', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='addpatient.assessment')),
            ],
        ),
    ]
