# Generated by Django 6.0 on 2026-02-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addpatient', '0012_assessment_assessmentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='cure_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ml_analysis_result',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
