# Generated by Django 6.0 on 2026-02-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addpatient', '0014_patient_address_patient_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='assessment_reports/'),
        ),
    ]
