# Generated by Django 6.0 on 2026-02-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addpatient', '0016_assessment_reduction_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='algorithm_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
