# Generated by Django 6.0 on 2026-02-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addpatient', '0017_assessment_algorithm_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='healing_index',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
