# Generated by Django 6.0 on 2026-02-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addpatient', '0019_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttask',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
