# Generated by Django 6.0.1 on 2026-01-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role_type', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('admin', 'Admin')], max_length=10)),
                ('job_title', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('license_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('shift', models.CharField(blank=True, choices=[('Day', 'Day'), ('Night', 'Night')], max_length=10, null=True)),
                ('access_level', models.CharField(blank=True, choices=[('Full', 'Full'), ('Limited', 'Limited')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
