# Generated by Django 6.0 on 2026-01-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0003_admin_groups_admin_is_active_admin_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='department',
        ),
        migrations.AddField(
            model_name='admin',
            name='raw_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
