# Generated by Django 6.0 on 2026-01-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0004_remove_admin_department_admin_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='department',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
