# Generated by Django 6.0 on 2026-02-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0005_admin_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20),
        ),
    ]
