# Generated by Django 6.0 on 2026-02-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0006_activitylog_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('admin', 'Admin'), ('patient_coordinator', 'Patient Coordinator')], max_length=25),
        ),
    ]
