# Generated by Django 6.0.2 on 2026-02-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0007_alter_admin_role_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='assigned_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='office_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
