# Generated by Django 6.0 on 2026-02-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0008_admin_assigned_region_admin_office_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
