# Generated by Django 6.0 on 2026-02-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0010_systemfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='assigned_region',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='office_location',
        ),
    ]
