# Generated by Django 6.0.2 on 2026-02-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0011_remove_admin_assigned_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('admin', 'Admin')], max_length=25),
        ),
    ]
