# Generated by Django 6.0 on 2026-02-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0012_alter_admin_role_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='password_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
