# Generated by Django 6.0 on 2026-03-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0013_admin_password_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='raw_password',
        ),
    ]
