# Generated by Django 6.0 on 2026-03-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0014_remove_admin_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
