# Generated by Django 6.0 on 2026-03-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0015_admin_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='country_code',
            field=models.CharField(default='+91', max_length=5),
        ),
    ]
