# Generated by Django 6.0 on 2026-03-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0016_admin_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
