# Generated by Django 6.0 on 2026-03-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0017_alter_admin_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
