# Generated by Django 6.0 on 2026-03-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursetask',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20),
        ),
    ]
